version: '3'
services:
  test:
    image: crccheck/hello-world
  webapp:
    image: localhost:5000/calculator-wui:test
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
  database:
    image: localhost:5000/calculator-db:test
    restart: always
  geoserver:
    image: localhost:5000/calculator-geoserver:test
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
