version: '3'
services:
  webapp:
    image: calculator-wui:test
    ports:
     - "8000:8080"
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
  database:
    image: calculator-db:test
    ports:
     - "5432:5432"
    restart: always
  geoserver:
    image: calculator-geoserver:test
    ports:
     - "8001:8080"
    depends_on:
      - "database"
    command: ["./wait-for-postgres.sh", "database", "catalina.sh", "run"]
    restart: always
