version: '3'
services:
  webapp:
    image: "{{service.CALCULATOR_WUI.hash}}"
    links:
     - "database:calculator-db"
    depends_on:
     - "database"
     - "geoserver"
  database:
    image: "{{service.CALCULATOR_DATABASE.hash}}"
  geoserver:
    image: "{{service.CALCULATOR_GEOSERVER.hash}}"
